version: 2

models:
  - name: stg_organizations
    description: "Staging table for organizations data"
    columns:
      - name: organization_id
        description: "Primary key for organizations"
        tests:
          - unique
          - not_null
      - name: created_Date
        description: "Record creation date in the database"
        tests:
          - not_null

  - name: stg_invoices
    description: "Staging table for invoices data"
    columns:
      - name: invoice_id
        description: "Primary key for invoices"
        tests:
          - unique
          - not_null
      - name: organization_id
        description: "Foreign key to organizations"
        tests:
          - not_null
      - name: amount
        description: "Invoice amount"
        tests:
          - not_null
          - accepted_values:
              values: ['>=0']  
      - name: status
        description: "Payment Status"
        tests:
          - accepted_values:
              values: ['paid', 'pending', 'skipped', 'open', 'cancelled', 'credited', 'failed', 'refunded', 'processing']  

     - name: dim_organizations
       description: "data with organization level data with invoice information"
       columns:
      - name: organization_id
        description: "Primary key for dim organizations"
        tests:
          - unique
          - not_null

     - name: fct_daily_balances
       description: "Fact table capturing daily balance snapshots"
       columns:
      - name: balance_date
        description: "Date of the balance snapshot"
        tests:
          - not_null
      - name: organization_id
        description: "Foreign key to dim_organizations"
        tests:
          - not_null
      - name: daily_balance
        description: "Balance amount for the day"
        tests:
          - not_null
