version: 2
sources:
  - name: raw
    tables:
      - name: organizations
        external:
          location: 'path/to/Organizations.csv'
      - name: invoices
        external:
          location: 'path/to/Invoices.csv'
